# Basic config
baseURL = "https://chensl.me"
theme = "hugo-simple"
languageCode = "zh-Hans"           # en
defaultContentLanguage = "zh"
hasCJKLanguage = true
title = "Chensl's Blog"
copyright = "© 2024 Shaolong Chen"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

enableInlineShortcodes = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug/"

[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# lineNos = true
# lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Chensl's Blog"
description = "只有非常努力，才能显得毫不费力"
# favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
mainSections = ["blog"]

[params.author]
name = "Shaolong Chen"
email = "shaolong.chen@outlook.it"
fediverse = "@chensl@purr.onl"

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menu.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[services.rss]
limit = 42

[pagination]
pagerSize = 16

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
